apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/minio/minio-operator/master/minio-operator.yaml
patchesStrategicMerge:
  - operator.yaml
