apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: minio-event-source
spec:
  type: minio
  minio:
    new-data-notification:
      bucket:
        name: input
      endpoint: minio-internal-service.devconf.svc:9000
      events:
        - s3:ObjectCreated:Put
      insecure: true
      accessKey:
        key: accesskey
        name: artifacts-minio
      secretKey:
        key: secretkey
        name: artifacts-minio
